language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: VmwhhhLIXkvOscM9h8NhXhUHGVC/R8M8DSX98h573S9yJml4YgepzjGYNfGdTMe99H3JBd2FNGyICkAHwONWv6faeQKrvFAQAOI5AfjDutHdG0bXHVcLLldk1lnVMPEsAtYurVvJoSc+r6FkzGbe4vYw5GhqV+10QTXCmnUJmW+uq5QrrnluQpTRUA9gJ3H83T1c9NY1JVc+L5xfROl2Bf8NDQcV9iHqCR4lWtEawI/28MRCseeVlBHtLnnpCRkM8Ub3a3WOX/KJh9ze2LRoagmLuzho6f+sxvdwgRxD62pqZm/T8WYPRAg43zIbsXBbvPgMXjgb+VYk8J8ZfJyMN+NWPWp0Whv5COu0WkK/RM5iBRLJdunuB5i+RjKWYMlfx1t9R/Xbn8F1C19imjEMqlxlDufaFcRj0B2Iw5zC+emTZC82q5XM5wUNiH2D3SUYXpz0h7AzQhrDyQdWEg0ZAWyMixCC9FZQXylLiAU0SlO6svJEHz8fR5ZVrqbWc2p0XEfFs9Tw/YGmR2y/Q+SskTbly4Ci+cB+S5xW7mC07EDhkhiQWf40NbrmGtA86ab9PefDTFuinrUs6JeHm+iaI5YimQu4CMLuVK1Ukaou9kOSmYtRxd3ujOiTCwM8BIlyTlZKYQ+oifhN+0Vjt9o0zcahobnO2eGNihGZYon2of0=
  - secure: mmjtbfbRtcdVBBfeSLTGbpyrTsN6AhwTi2QGJrxWoFdG0fOMMXmYiQbm3Cx/1WqgmVCzWNkgjECWDgKquEbf2CL+wfPElwB8zMqibTzxZxIgS0JAJ5fdgAq+TQqJOsxTCek1Ie9lul/wgarNOvJZqxuMY74ipJpBJlgQ3RpDdiW80C0Ms7tsLrb6SAuwrd40+bZ2eVFiOZ3mdRbyVoPuPT6F4sVnKnALJn4GwqQi+wTmC09wAOt0vEA7qz2sw95/Tlsqk7ZydxN3zsgQMVtTbBmW7DAgXBcYMwggtDwoT3eh7taf9T7D/yMDRY1zaXLFN/BblKSszdNWF4nyWoeWaxvA0y3l1Y3DS+XqZGVb6WQISNuXGxsQMUpgJcazeLJVtA1CZEzNIe8VKtieUnixZPu2C8mhDn2mqP3yL+xFvkyiBROXJ2wawCxSgaYnr8gjCJoNSH27chNVTfvfOlpwVGhHgvlzX8kT0on1pDx+eLs3eGJ5te6zCiu+xc6mey8/cYGcZf8mQJNJl5RGHC80KoF3S0NitjEl/Kl3NFNymnNWpYcgLhHw11r+zRfs4/zXQYjaIJMbFXdOo0G22+0QfaZ+WP1KnpGP/+ai64351BhOAUvchG0MipTKLbrD7nTI/06fULxC8FFQMOdZyPq1l8rRqyiZiqdbJ9e67PLwMoI=
  - secure: k7HQgWG2MWvXz/Vwa/BMPQosa4CubmEntTfsygmCM9lPRgs42rDXGKoE1nQA9Y1iRZTYYxGpvB4YCNdaGtOfetRftUuvqTKiP7wndQyx9mS/aOsIYw6ryOylqw0Ho6I3CdCvIDf7i1XExS8uwx0JonyincwFKSWwCQJwx8dO098kXnlJiACUPkQ3OrafSJwJjjMRu3S/1GZfgqe3DFUXrBDFgRRNoUlzHFcOzpWdpjIrD87TbKuNkHzUPKRwz/9YdUxS3S0mVadoiIeOY+E+4wAxwcy/rOJk08A8Ri1xH3zCc0mJQ4z/tDgQqG/OHlfyarFG7PA0h/HrMWH/Vag9tN8hc6UDAly+kt0h6x+NtOHeXpHIaa8jm174UoGa3mO/BvkKOkTWq51wbVHYA4HPFNM2datEbZjY+J5Hs99QLIHgm49fHnZLyIn3GRMdYSi1OYKRVqwYLwKFDC7lgO0o+xP047X2EpuswPi3szu7342/kXvK2RcYvG3Y1clvuV2skdbL4vWc1JzhQsDHJhqSaC7Q7oaCA9YOjjqMu4XX2/RnUNoXQiAaTfwxvIKbYuqCOivvqOBdDrFRK+yl/pVcwP8/5ySvdnlsFris1cl9v/Ord5mtKtiT862WHjVtIVO5GSaqTwmdvQIzpZ92C4zYlozN4fEO261SJt0rMGoVKU4=
